#!/usr/bin/env bash

# This file needs lots of refactoring

if [ -z "$PS1" ]; then
  echo -e "${COLOR_RED}You should source this, not run it, for example: source link${COLOR_NC}\n\n"
fi

rm ~/.bash_profile
rm ~/.bashrc
rm ~/.bashrc_help
rm ~/.bashrc_app_specific
rm ~/.dir_colors

ln -s ~/dotfiles/etc/bash_profile ~/.bash_profile
ln -s ~/dotfiles/etc/bashrc ~/.bashrc
ln -s ~/dotfiles/etc/bashrc_help ~/.bashrc_help
ln -s ~/dotfiles/etc/bashrc_app_specific ~/.bashrc_app_specific
ln -s ~/dotfiles/etc/dir_colors ~/.dir_colors

# vim
rm ~/.vimrc
rm ~/.vim

ln -s ~/dotfiles/etc/vim/vimrc ~/.vimrc
ln -s ~/dotfiles/etc/vim ~/.vim


# irb
rm ~/.irbrc
ln -s ~/dotfiles/etc/irbrc ~/.irbrc

# git
rm ~/.gitignore
rm ~/.gitattributes
# ln -s ~/dotfiles/etc/gitconfig ~/.gitconfig
ln -s ~/dotfiles/etc/gitignore ~/.gitignore
ln -s ~/dotfiles/etc/gitattributes ~/.gitattributes

source ~/.bash_profile
